Update navigation_from_list_to_edit.md
- Fixed typo: _"intent"_ to _"intend".
- Fixed typo: `playersRow` to `playerRow`.
- Added `editBtn` in `playerRow` function.
- Add `import Hop` in **src/Players/Actions.elm** otherwise you'd see the following error:

```
-- NAMING ERROR -------------------------------------- ./src/Players/Actions.elm

Cannot find type `Hop.Action`.

9│   | HopAction Hop.Action
                 ^^^^^^^^^^
The qualifier `Hop` is not in scope. Maybe you want one of the following?

    Http.Action
```

- Fixed changes to **src/Players/Update.elm**. Handling `HopAction` is
  also required because it was added to **src/Players/Actions.elm**,
  otherwise you'd see the following error:

```
-- MISSING PATTERNS -----------------------------------
./src/Players/Update.elm

This `case` does not have branches for all possibilities.

14│>  case action of
15│>    EditPlayer id ->
16│>      let
17│>        path =
18│>          "/players/" ++ (toString id) ++ "/edit"
19│>      in
20│>        ( model.players, Effects.map HopAction (Hop.navigateTo path)
)
21│>
22│>    NoOp ->
23│>      ( model.players, Effects.none )

You need to account for the following values:

    Players.Actions.HopAction _

    Add a branch to cover this pattern!

    If you are seeing this error for the first time, check out these
    hints:
    <https://github.com/elm-lang/elm-compiler/blob/0.16.0/hints/missing-patterns.md>
    The recommendations about wildcard patterns and `Debug.crash` are
    important!
```